mongodb:
        host: mongodb://username:password@localhost:27017/dbname

redis:
    host: localhost
    port: 6379
    password: my secret password

api:
    use_anonymous: yes

bitly:
    token: ihjwb498ubo4v898b9ebuojmdvmbdjkgoipj42us

cron:
    key: ihjwb498ubo4v898b9ebuojmdvmbdjkgoipj42us

logger: &logger
    version: 1
    formatters:
        beepasteFormater:
            format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
            datefmt: '%Y/%m/%d %H:%M:%S'
    handlers:
        file:
            class : logging.FileHandler
            formatter: beepasteFormater
            level: INFO
            filename: beepaste.log
            # maxBytes: 52428800
            # backupCount: 20
        console:
            class : logging.StreamHandler
            formatter: beepasteFormater
            level: INFO
            stream: ext://sys.stdout
    loggers:
        beepaste:
            level: INFO
            handlers: [file]
            qualname: beepaste
            propagate: false
        sanic:
            level: INFO
            handlers: [file]
            qualname: sanic
            propagate: false
        network:
            level: INFO
            handlers: [file]
            qualname: network
            propagate: false
    root:
        level: INFO
        handlers: [file]

web_server:
    port : 8080
    host : localhost
    workers: 8
    log_config: *logger
