mongodb:
    image: mongo
#    ports:
#        - 27017:27017
    volumes:
        - ./data:/data/db

redis:
    image: redis
#    ports:
#        - 6379:6379

backend:
    build: backend/
    ports:
        - 8080:8080
    links:
        - mongodb:mongodata
        - redis:redisdata
