mongodb:
    build: mongodb
    ports:
        - 27017:27017
    environment:
        MONGODB_USER: beepasteio
        MONGODB_PASS: imavcandoit
        MONGODB_DATABASE: beepaste
    volumes:
        - ./data:/data/db
