mongodb:
    image: mongo
#    ports:
#        - 27017:27017
#    volumes:
#        - ./data:/data/db
    restart: always

redis:
    image: redis
#    ports:
#        - 6379:6379
    restart: always

backend_1:
    image: beepaste_back
    ports:
        - 8080:8080
    volumes:
        - ./config:/beepaste/config
    links:
        - mongodb:mongodata
        - redis:redisdata
    restart: always
backend_2:
    image: beepaste_back
    # ports:
    #     - 8080:8080
    volumes:
        - ./config:/beepaste/config
    links:
        - mongodb:mongodata
        - redis:redisdata
    restart: always
backend_3:
    image: beepaste_back
    # ports:
    #     - 8080:8080
    volumes:
        - ./config:/beepaste/config
    links:
        - mongodb:mongodata
        - redis:redisdata
    restart: always
backend_4:
    image: beepaste_back
    # ports:
    #     - 8080:8080
    volumes:
        - ./config:/beepaste/config
    links:
        - mongodb:mongodata
        - redis:redisdata
    restart: always


frontend_1:
    image: beepaste_front
    ports:
        - 8081:3000
    restart: always
frontend_2:
    image: beepaste_front
    # ports:
    #     - 8081:3000
    restart: always
frontend_3:
    image: beepaste_front
    # ports:
    #     - 8081:3000
    restart: always
frontend_4:
    image: beepaste_front
    # ports:
    #     - 8081:3000
    restart: always


nginx:
    image: beepaste_nginx
    ports:
        - 8082:80
    links:
        - backend_1:backend_server_1
        - backend_2:backend_server_2
        - backend_3:backend_server_3
        - backend_4:backend_server_4
        - frontend_1:front_server_1
        - frontend_2:front_server_2
        - frontend_3:front_server_3
        - frontend_4:front_server_4