mongodb:
    host: mongodb://mongodata:27017/beepaste

redis:
    address: !!python/tuple ['redisdata', 6379]
#    password: my secret password
    db: 0

limits:
    reset_timeout: 900
    auth_timeout: 2592000
    create_paste: 450
    get_paste: 450

api:
    use_anonymous: yes

bitly:
    token: ihjwb498ubo4v898b9ebuojmdvmbdjkgoipj42us

cron:
    key: ihjwb498ubo4v898b9ebuojmdvmbdjkgoipj42us

logger: &logger
    version: 1
    formatters:
        beepasteFormater:
            format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
            datefmt: '%Y/%m/%d %H:%M:%S'
    handlers:
        file:
            class : logging.FileHandler
            formatter: beepasteFormater
            level: INFO
            filename: beepaste.log
            # maxBytes: 52428800
            # backupCount: 20
        console:
            class : logging.StreamHandler
            formatter: beepasteFormater
            level: INFO
            stream: ext://sys.stdout
    loggers:
        beepaste:
            level: INFO
            handlers: [file]
            qualname: beepaste
            propagate: false
        sanic:
            level: INFO
            handlers: [console]
            qualname: sanic
            propagate: false
        network:
            level: INFO
            handlers: [console]
            qualname: network
            propagate: false
    root:
        level: INFO
        handlers: [file]

app:
    port : 8080
    host : 0.0.0.0
    workers: 8
    log_config: *logger
    debug: True

jwt:
    secret: secret # TODO on production use some safe string
    algorithm: HS512
